// Code generated by MockGen. DO NOT EDIT.
// Source: index_service.go

// Package web is a generated GoMock package.
package web

import (
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIndexServiceInterface is a mock of IndexServiceInterface interface
type MockIndexServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIndexServiceInterfaceMockRecorder
}

// MockIndexServiceInterfaceMockRecorder is the mock recorder for MockIndexServiceInterface
type MockIndexServiceInterfaceMockRecorder struct {
	mock *MockIndexServiceInterface
}

// NewMockIndexServiceInterface creates a new mock instance
func NewMockIndexServiceInterface(ctrl *gomock.Controller) *MockIndexServiceInterface {
	mock := &MockIndexServiceInterface{ctrl: ctrl}
	mock.recorder = &MockIndexServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIndexServiceInterface) EXPECT() *MockIndexServiceInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockIndexServiceInterface) Get() func(*gin.Context) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(func(*gin.Context))
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockIndexServiceInterfaceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIndexServiceInterface)(nil).Get))
}

// NotAllowed mocks base method
func (m *MockIndexServiceInterface) NotAllowed() func(*gin.Context) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotAllowed")
	ret0, _ := ret[0].(func(*gin.Context))
	return ret0
}

// NotAllowed indicates an expected call of NotAllowed
func (mr *MockIndexServiceInterfaceMockRecorder) NotAllowed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotAllowed", reflect.TypeOf((*MockIndexServiceInterface)(nil).NotAllowed))
}

// RenderIndex mocks base method
func (m *MockIndexServiceInterface) RenderIndex() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderIndex")
}

// RenderIndex indicates an expected call of RenderIndex
func (mr *MockIndexServiceInterfaceMockRecorder) RenderIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderIndex", reflect.TypeOf((*MockIndexServiceInterface)(nil).RenderIndex))
}
